Task 1
mashasi98/surf_flutter_cources pull request #1
Opened 2024-04-29 09:55 UTC by mashasi98

2024-05-13 14:18 UTC, danyaao requested changes

2024-05-13 14:18 UTC, danyaao commented on lib/main.dart
> +enum Action {
Action не очень явно нам говорит, за что отвечает этот энам. В небольшом задании это ок, но вообще лучше называть явно, к примеру, CounterAction

2024-05-13 14:18 UTC, danyaao commented on lib/main.dart
> +  String someString = "";
Плохое название переменной)

2024-05-13 14:18 UTC, danyaao commented on lib/main.dart
> +  void Function()? _setCounterState(Action action) {
Не совсем понял, а зачем тут анонимная функция? Можно просто оставить void и все действия выполнять в теле основного метода

2024-05-13 14:18 UTC, danyaao commented on lib/main.dart
> +          setButton(Action.increment, Action.increment.toString(),
Возвращать виджеты из функций - плохая практика. К примеру, так ты не сможешь смотреть на структуру во Flutter инспекторе. Да и в целом у нас же ООП, а не функциональное программирование. Давай прямо здесь использовать непосредственно кнопки, а в них уже передавать нужные функции в onPressed. Если хочешь, кнопки можно вынести как stateless виджеты

2024-05-13 14:18 UTC, danyaao commented on lib/main.dart
> +          setButton(Action.decrement, Action.decrement.toString(),
Я правильно пониманию, что изначально someString должна была отображать текст ошибки отрицательного значения? Можно бы добавить

2024-05-14 12:52 UTC, mashasi98 commented on lib/main.dart
> +  String someString = "";
@danyaao невнимательное название переменное ) забыла ее отрефачить )

2024-05-15 09:25 UTC, mashasi98 commented on lib/main.dart
> +          setButton(Action.decrement, Action.decrement.toString(),
some string вообще не должно было быть )

2024-05-27 19:55 UTC, danyaao approved these changes

2024-05-27 19:55 UTC, danyaao commented on lib/task-1/main.dart
> +  late int _decrementCounts = 0;
Тут late не нужен, ты сразу значение присваиваешь

2024-05-30 08:57 UTC, merged